"""Estados y claves compartidas del cotizador v1."""

ESTADO_OK = "OK"
ESTADO_NO_ENCONTRADO = "NO_ENCONTRADO"
ESTADO_SIN_SELECCION = "SIN_SELECCION"
ESTADO_SKIPPED = "SKIPPED"
ESTADO_ERROR = "ERROR"
ESTADO_REQUIERE_REVISION = "REQUIERE_REVISION"

ESTADOS_COTIZACION = {
    ESTADO_OK,
    ESTADO_NO_ENCONTRADO,
    ESTADO_SIN_SELECCION,
    ESTADO_SKIPPED,
    ESTADO_ERROR,
    ESTADO_REQUIERE_REVISION,
}
